fix: updated images docs
codestore-solutions/FeedbackManagement pull request #27
Opened 2023-08-09 08:25 UTC by ravikunwar099

2023-08-09 11:37 UTC, tu-sh-ar commented on FeedbackBackend/build/constants/customer.js
Please add comments on this as this is not part of the Actual code.

2023-08-09 11:38 UTC, tu-sh-ar commented on FeedbackBackend/build/constants/delivery.js
Please add comments on this as this is not part of the Actual code.

2023-08-09 11:38 UTC, tu-sh-ar commented on FeedbackBackend/build/constants/products.js
Please add comments on this as this is not part of the Actual code.

2023-08-09 11:44 UTC, tu-sh-ar requested changes
Please make the required changes

2023-08-09 11:44 UTC, tu-sh-ar commented on FeedbackBackend/src/controllers/responseController.ts
Please make sure to save any file with their Name only not with the full name.
Eg. https://example.com/uploads/img.jpg --> {https://example.com} baseUrl, {/uploads/img.jpg} File name to be stored

2023-08-09 12:08 UTC, ravikunwar099 commented on FeedbackBackend/src/controllers/responseController.ts
I will create a separate MR for this, and we can't update this currently because the current flow depends on this format (https://base_url/file_name), so we can leave this as it is for now 
we can use this format ((https://example.com/) baseUrl, {/uploads/img.jpg} File name to be stored) whenever DB gets cleaned

2023-08-09 12:11 UTC, tu-sh-ar approved these changes

2023-08-10 06:25 UTC, varun-codestore commented on FeedbackBackend/src/constants/feedback templates/products.ts
Please rename the folder name that can be break due to space in the Folder Name ("feedback templates"), that can be break on deployment.

2023-08-10 06:25 UTC, varun-codestore commented on FeedbackBackend/src/constants/feedback templates/seller.ts
Please rename the folder name that can be break due to space in the Folder Name ("feedback templates"), that can be break on deployment.

2023-08-10 06:53 UTC, varun-codestore approved these changes

2023-08-11 05:46 UTC, tu-sh-ar approved these changes

2023-08-11 06:09 UTC, GarvCS approved these changes

2023-08-11 06:09 UTC, merged